### ISSUE TITLE
Customize output

### ISSUE THREAD

**Issue by szaghi** [pdebuyl/fortran_tester#11]
Dear Pierre, 

I am using your cool library more and more... I love it. For example, I just add it into FLAP tests suite, see [this](https://github.com/szaghi/FLAP/issues/71#issuecomment-256027489). 

I have another little question. Consider the following output:

``` shell
tefano@zaghi(02:32 PM Tue Oct 25) on feature/group-default-values-bug-fix [+!?]
~/fortran/FLAP 17 files, 152Kb
→ ./exe/test_group
 test_group
 spectrum =  F
 domain   =  F
 grid     =  F
 test_group new -s
 spectrum =  T
 domain   =  F
 grid     =  F
 test_group new -d
 spectrum =  F
 domain   =  T
 grid     =  F
 test_group new -g
 spectrum =  F
 domain   =  F
 grid     =  T
 fortran_tester:           0  error(s) for          12 test(s)
 fortran_tester: all tests succeeded
```

Do you think you could like to _customize_ the last output? I mean, now the string `fortran_tester:` is automatically added, but it could be easily _customizable_ passing an optional argument to the tester `init` method. Having the possibility to customize this prefix could help to `grep many outputs with one script`. If you like the idea, I can create a pull request.

As always, thank you!

**Comment by pdebuyl** [comment]
Hi Stefano,

I wanted to check FLAP first, to see how fortran_tester is used. I have a modest PR that enables a cmake build with testing https://github.com/szaghi/FLAP/pull/72

I am not sure I understand what you would like. Something like an optional argument to the init subroutine and an allocatable character?

```
  character(len=:), allocatable :: header
```

**Comment by szaghi** [comment]
@pdebuyl 

Hi Pierre, I just accepted your PR, thank you very much!

Yes, exactly it. However, it is not FLAP the case where I like to customize it rather on HASTY: I write many tests, thus I like to have a bash script to collect some statics... simply relying on `grep`... customizing the header could help (for HASTY I resolved grepping " error(s)" string, but for future could be helpful.

**Comment by pdebuyl** [comment]
Ok, that seems reasonable, backwards-compatible option :-)

You can think of having one "success" string and one "failure" string too.

BTW, CMake testing integration is great!

**Comment by szaghi** [comment]
@pdebuyl 

> You can think of having one "success" string and one "failure" string too.

Great!

> BTW, CMake testing integration is great!

I know, but I am too lazy to learn a new tool... BTW for (only) Fortran tests also FoBiS is cool, see [doctest](https://github.com/szaghi/FoBiS/wiki/doctests) :smile:

**Comment by pdebuyl** [comment]
Hi @szaghi do you have an update on this topic? I would like to either close the issue (if the need is not really there) or think about it more deeply.

Options:
1. Just add user-defined "success" and "failure" strings.
2. I also thought of adding a `set_name` routine that defines the name of the following test(s). This avoid manipulating strings for the case of repeated testings (I sometimes iterate over simple test cases). The first test failure would be recorded and given in output, as in
``First failure at test: my test name``
  so you could at least find the first failure easily.
3. The unlikely option: use a similar `set_name` routine (or pass a name for each test) and store the number of failure per test name (via a hash table) to give a full report. I don't have a easy solution for the hash table though.

**Comment by szaghi** [comment]
@pdebuyl 

I am very sorry. Currently (last n-months) I am in a "nightmare work-phase", I have litterally zero-time for Fortran projects. I am very sorry, but for now I cannot help. Feel free to withdraw this issue.

Cheers.

**Comment by pdebuyl** [comment]
ok @szaghi feel free to reopen later if needed.
