### ISSUE TITLE
'error stop' not supported by PGI

### ISSUE THREAD

**Issue by bonfus** [pdebuyl/fortran_tester#13]
According to [fortranwiki](http://fortranwiki.org/fortran/show/Fortran+2008+status) `error stop` is not supported by PGI. Indeed compilation with PGI 17.10 fails at this line

https://github.com/pdebuyl/fortran_tester/blob/48e344f2a9aea58e597259da343735b137ca1fea/src/tester.f90#L153

Changing that to

    #if ! defined(__PGI)
          error stop 'fortran_tester: tests failed'
    #else
          stop 1
    #endif

Intel 15+ and Cray compilers work fine with the `error stop`.

**Comment by pdebuyl** [comment]
Hi @bonfus thank you for the report.

I avoid any type of preprocessing in `fortran_tester` on purpose, I want it to be dependent on only a Fortran compiler.

Is the Portland Group not preparing an update of their compiler? Do you need to use them?

I see several options:
1. Use "stop 1", and that's it.
2. Duplicate the file, and PGI users can use the alternative.

Of course it is a bit annoying to be unable to use such a simple Fortran 2008 feature in 2018 :(

**Comment by bonfus** [comment]
> I avoid any type of preprocessing in fortran_tester on purpose, I want it to be dependent on only a Fortran compiler.

This totally makes sense, and it's actually one of the reasons why I like your module.
I included the modified version of `tester.f90` in the code that I'm developing where preprocessing is always done. It's not a big deal to change the relevant line when the tester is updated.
Feel free to close the issue and thanks for your support.

**Comment by pdebuyl** [comment]
Hi @bonfus 

`error stop` has a specific meaning for "coarray fortran" which I dare to guess is not use by users of `fortran_tester`. I switched to `stop 1` which should solve your issue.

Unless I receive some bad feedback about the change I see no reason to move back before this module is applied to coarray fortran codes.

**Comment by bonfus** [comment]
Switching to `stop 1` solves my problem, thank you.

**Comment by bonfus** [comment]
Just for reference: with GNU Fortran (7.2), `error stop` produces back-traces like this

    Error termination. Backtrace:
    #0  0x55c933f43284 in __tester_MOD_print
	    at /tmp/tests/tester.f90:154
    #1  0x55c933f3f0b4 in test_diaghg_3
	    at /tmp/tests/test_diaghg_3.f90:27
    #2  0x55c933f3f0b4 in main
	    at /tmp/tests/test_diaghg_3.f90:3

while `stop 1` doesn't.

**Comment by pdebuyl** [comment]
Yes, it was a bit annoying but I got used to the backtrace for test failures :-) With a cmake setup you don't see them anyway.
