### ISSUE TITLE
More informative output

### ISSUE THREAD

**Issue by szaghi** [pdebuyl/fortran_tester#6]
Dear @pdebuyl 

the output of the `print` method is somehow too much concise, e.g.

``` shell
stefano@zaghi(01:41 PM Fri Oct 14) on master [?]
~/fortran/fortran_tester 11 files, 3.3Mb
→ ./test_tester_2
 fortran_tester:           1  error(s) for           1 test(s)
fortran_tester: tests failed
```

It prints only the number of errors occurred. It could be useful to provide a more informative output. For example we could print which are the errors failed, the inputs provided to the test assert procedures... an approach could be to register such events into an array of _strings_. If you like, I can try to implement this feature.

What do you think?

**Comment by pdebuyl** [comment]
I would like to avoid this, at least for now. While this is a desirable feature, I think that keeping a limited scope to `fortran_tester` is best. If the library is to be used, the barrier to entry should remain low.

An alternative approach would be to use a preprocessor to provide automatically the filename and line of the error. This would be invasive though for the user and should remain optional.
