### ISSUE TITLE
fobos file

### ISSUE THREAD

**Issue by szaghi** [pdebuyl/fortran_tester#7]
Dear @pdebuyl 

It could be useful for me to have a fobos file (the makefile of FoBiS) in the project. Currently I simply do a `FoBiS build` that automatically builds all programs found (your tests), but for other  stuff (e.g. code coverage/debug) I like to use a fobos file. I do not want to pollute your tree, it could be named/placed where you want, even a hidden `.fobos` file is fine for me thus having a minimal impact on your clean tree. 

Do you think I can add a fobos file?

Cheers.

**Comment by pdebuyl** [comment]
yes, a fobos file is fine. Naming is `.fobos` would be ideal then

**Comment by szaghi** [comment]
Thanks!
